# This manifest tells ArgoCD to deploy your custom 'elastic-stack' umbrella chart.
# It will be committed to your main 'argocd-control-repo'.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Give your application a unique and descriptive name.
  name: elastic-stack-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  # The source configuration now points to your Git repository and your new chart.
  source:
    # This is your private repository where the 'elastic-stack' chart is located.
    repoURL: https://github.com/quentinstaples/elastic.git
    # The name of your custom umbrella chart.
    chart: elastic-stack
    # The branch of your Git repository to use.
    targetRevision: main

  # The destination defines where the application will be deployed in your cluster.
  destination:
    server: https://kubernetes.default.svc
    # It's a good practice to use a dedicated namespace for Elastic.
    namespace: elastic-system

  # The synchronization policy ensures that changes are automatically applied.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
