# This manifest tells ArgoCD to deploy your custom 'elastic-stack' umbrella chart.
# It will be committed to your main 'argocd-control-repo'.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Give your application a unique and descriptive name.
  name: sops-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: git@github.com:quentinstaples/argocd.git
    targetRevision: main
    path: sops-secrets-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: sops

  # The synchronization policy ensures that changes are automatically applied.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
